GET http://localhost:5015/visits
Accept: application/json

###
GET http://localhost:5015/visits/3
Accept: application/json

###
POST http://localhost:5015/visits
Content-Type: application/json

{
  "ReserverName": "Mini",
  "ReserverSurname": "Majk",
  "CatName": "Majkel",
  "CatAgeInMonths": 43,
  "CatColor": "Gray",
  "visitDate": "2024-10-02T10:00:00"
}

###
DELETE http://localhost:5015/visits/2